language: node_js
node_js:
  - '12'
  - '10'
branches:
  only:
    - master
cache:
  yarn: true
services:
  - mongodb
before_script:
  - yarn install
os:
  - linux
script:
  - yarn test
  - yarn coverage
