language: node_js
node_js:
  - '12'
  - '10'
branches:
  only:
    - master
cache:
  directories:
  - node_modules
services:
  - mongodb
before_script:
  - npm install
os:
  - linux
script:
  - npm run test:coverage
  - npm run coverage
